name: Final Fix

on: workflow_dispatch

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - name: Check runners
        run: |
          echo "Runner connected!"
          hostname
          date